language: python
python:
    - "3.6"
install: "pip install -r requirements.txt"
script: 
    - python ./main.py add webhook None --test
    - python ./main.py add feed https://www.theregister.co.uk/personal_tech/headlines.atom
    - python ./main.py link 1 1
    - python ./main.py list webhook
    - python ./main.py list feed
    - python ./main.py list link
    - python ./main.py run --runonce
